import re
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, HttpUrl
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled, NoTranscriptFound
from app.api.deps import get_current_user
from app.models.user import User

router = APIRouter()

def deduplicate_transcript(text: str) -> str:
    """
    Remove consecutive repeated sentences or word sequences from YouTube auto-caption text.
    YouTube often emits the same phrase 2-3 times in successive segments.
    """
    if not text:
        return text

    # First, normalize whitespace
    normalized_text = re.sub(r'\s+', ' ', text).strip()
    
    # Split into words
    words = normalized_text.split()
    n = len(words)
    if n < 2:
        return normalized_text

    # Remove consecutive repeating sequences of words of length k (from 1 up to 15 words)
    # E.g. "hello world hello world" -> "hello world"
    i = 0
    while i < len(words):
        deduped_any = False
        for k in range(1, 16):
            if i + 2 * k <= len(words):
                seq1 = words[i : i + k]
                seq2 = words[i + k : i + 2 * k]
                if seq1 == seq2:
                    del words[i + k : i + 2 * k]
                    deduped_any = True
                    break
        if not deduped_any:
            i += 1

    return ' '.join(words)

class TranscriptRequest(BaseModel):
    url: str

class TranscriptResponse(BaseModel):
    video_id: str
    transcript: str

def extract_video_id(url: str) -> str:
    # Match standard watch URL, share URL, embed URL, shorts URL, and direct 11-char ID
    regex = r'(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|shorts\/|.*[?&]v=)|youtu\.be\/|^)([^"&?\/\s]{11})'
    match = re.search(regex, url)
    if not match:
        raise ValueError("Invalid YouTube URL. Could not parse Video ID.")
    return match.group(1)

@router.post("/generate", response_model=TranscriptResponse)
def generate_transcript(payload: TranscriptRequest, current_user: User = Depends(get_current_user)):
    try:
        video_id = extract_video_id(payload.url)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    
    try:
        yt_api = YouTubeTranscriptApi()
        transcript_list = yt_api.list(video_id)
        try:
            # Try to fetch English first
            transcript_obj = transcript_list.find_transcript(['en'])
        except Exception:
            # Fallback to any available language
            transcript_obj = next(iter(transcript_list))
            
        fetched_lines = transcript_obj.fetch()
        raw_transcript = " ".join([entry.text for entry in fetched_lines])
        full_transcript = deduplicate_transcript(raw_transcript)
        return TranscriptResponse(video_id=video_id, transcript=full_transcript)
    except TranscriptsDisabled:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Transcripts are disabled for this video."
        )
    except NoTranscriptFound:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No transcript was found for this video."
        )
    except Exception as primary_error:
        import traceback
        traceback.print_exc()
        
        # Fallback to youtube-transcript.ai to bypass cloud provider IP block
        try:
            import httpx
            fallback_url = f"https://youtube-transcript.ai/transcript/{video_id}.txt"
            res = httpx.get(fallback_url, timeout=12.0)
            if res.status_code == 200 and res.text:
                lines = res.text.split("\n")
                transcript_lines = []
                for line in lines:
                    line = line.strip()
                    if not line:
                        continue
                    # Skip headers/footers
                    if (line.startswith("#") or 
                        line.startswith("Source video:") or 
                        line.startswith("Language:") or 
                        line.startswith("---") or 
                        "Generated by" in line or 
                        "Interactive version" in line):
                        continue
                    
                    # Strip timestamps like [0:02], [10:15]
                    line = re.sub(r"^\[\d+(?::\d+){1,2}\]\s*", "", line)
                    if line:
                        transcript_lines.append(line)
                
                full_transcript = deduplicate_transcript(" ".join(transcript_lines))
                if full_transcript:
                    return TranscriptResponse(video_id=video_id, transcript=full_transcript)
        except Exception as fallback_error:
            print(f"Fallback transcript generation failed: {fallback_error}")
            traceback.print_exc()
            
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching the transcript: {str(primary_error)}"
        )
